upgraded sdk to 1.11.0
nokia/industrial-application-framework pull request #12
Opened 2021-09-08 12:49 UTC by tothattila08

2021-09-08 12:50 UTC, tothattila08 commented
@hochdorf

2021-09-09 08:33 UTC, hochdorf commented on .github/workflows/go.yml
>      - name: Setup operator-sdk Action
this operator-sdk action is not needed anymore

2021-09-09 12:05 UTC, hochdorf requested changes

2021-09-09 12:05 UTC, hochdorf commented on consul-operator/deploy/olm-catalog/consul/0.0.1/consul.v0.0.1.clusterserviceversion.yaml
> -# Copyright 2020 Nokia
is there a way to still have a csv and other olm related resources in the repo? sanbox env uses these to deploy the consul op.

2021-09-10 07:21 UTC, hochdorf commented
you moved the storage_for_db.yaml file from the res-req dir to the root (consul-operator/storage_for_db.yaml), why?

2021-09-10 07:25 UTC, hochdorf requested changes

2021-09-10 07:25 UTC, hochdorf commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> -# Copyright 2020 Nokia
pls put back the copyright clause

2021-09-10 07:25 UTC, hochdorf commented on consul-operator/packagemanifests/consul-operator-new.package.yaml
> +- currentCSV: consul-operator-new.v0.0.1
can we keep the old name? just consul, instead of the the consul-operator-new?

2021-09-10 07:25 UTC, hochdorf commented on consul-operator/packagemanifests/0.0.1/consul-operator-new.clusterserviceversion.yaml
> -  - supported: true
would be better to change to back to true

2021-09-10 07:25 UTC, hochdorf commented on consul-operator/packagemanifests/0.0.1/consul-operator-new.clusterserviceversion.yaml
> +  - supported: false
would be better to change to back to true

2021-09-10 07:25 UTC, tothattila08 commented
> you moved the storage_for_db.yaml file from the res-req dir to the root (consul-operator/storage_for_db.yaml), why?

just to test the operator locally, and forgot to put it back :)

2021-09-10 09:22 UTC, hochdorf commented on consul-operator/packagemanifests/0.0.1/consul.clusterserviceversion.yaml
> +  name: consul-operator-new.v0.0.1
it is not in sync with the package, can you modify this to have only consul.v0.0.1 everywhere instead of this new consul-op....

2021-09-10 09:36 UTC, hochdorf approved these changes

2021-09-10 09:46 UTC, merged