Componenttests
nokia/industrial-application-framework pull request #35
Opened 2022-03-02 13:01 UTC by bisztray

Added component tests

2022-03-04 08:18 UTC, howardhalili commented on .github/workflows/go.yml
> +    - name: Download component test binaries
not running the test?

2022-03-04 08:22 UTC, bisztray commented on .github/workflows/go.yml
> +    - name: Download component test binaries
the docker build runs the tests

2022-03-04 08:29 UTC, howardhalili commented on .github/workflows/go.yml
> +    - name: Download component test binaries
can please add -race flag to go test for race condition detection?

2022-03-04 08:42 UTC, howardhalili commented on consul-operator/componenttest/constants.go
> +var networks = []appdacnokiacomv1alpha1.Network{{ApnUUID: apnUUID, AdditionalRoutes: []string{"127.0.1.1/28", "127.0.1.2/28"}}}
not that important but maybe a better example for additional routes, current values are actually in the same network

2022-03-04 08:58 UTC, howardhalili approved these changes

2022-03-04 08:58 UTC, howardhalili commented on consul-operator/componenttest/story_deploy_undeploy_test.go
> +			It("But keeps the stateful set intact", func() {
maybe add Service (k8s resource) removal check

2022-03-04 08:58 UTC, howardhalili commented on consul-operator/componenttest/story_deploy_undeploy_test.go
> +			It("Sets the appStatus is to running", func() {
maybe add Service (k8s resource) recreation check

2022-03-04 10:45 UTC, hochdorf requested changes

2022-03-04 10:45 UTC, hochdorf commented on componenttest-lib/pkg/env/suite_env.go
> +	LocalCfg.KubeConfig, err = getFilenameFromDirectoryByExtension(LocalCfg.CertDir, "kubecfg")
can you pls print the location of the kubeconfig? it would help a lot the debugging

2022-03-04 10:45 UTC, hochdorf commented on consul-operator/componenttest/constants.go
> +package componenttest
nokia licence header should be added to all of the files

2022-03-04 10:45 UTC, hochdorf commented on consul-operator/componenttest/mock/mockoperator.go
> +package mock
do you really use this anywhere?

2022-03-04 10:45 UTC, hochdorf commented on consul-operator/componenttest/story_deploy_undeploy_test.go
> +			It("executes consul CR", func() {
consul CR is created by the appfw

2022-03-04 10:47 UTC, hochdorf commented
something id not fully ok in the pipeline, it seems like the test was not executed:
```
KUBEBUILDER_ASSETS="/home/runner/.local/share/kubebuilder-envtest/k8s/1.21.4-linux-amd64" go test -race -ginkgo.v ./... -coverprofile cover.out
?   	github.com/nokia/industrial-application-framework/consul-operator	[no test files]
docker build -t consul-operator:test .
```

2022-03-04 12:01 UTC, bisztray commented on componenttest-lib/pkg/env/suite_env.go
> +	LocalCfg.KubeConfig, err = getFilenameFromDirectoryByExtension(LocalCfg.CertDir, "kubecfg")
It is done in story_deploy_undeploy_test.go line 56

2022-03-10 08:01 UTC, hochdorf commented on consul-operator/componenttest/constants.go
> +package componenttest
@bisztray not addressed pls check and commen if ready

2022-03-10 08:03 UTC, hochdorf commented on consul-operator/componenttest/mock/mockoperator.go
> +package mock
@bisztray not addressed

2022-03-10 08:03 UTC, hochdorf commented on consul-operator/componenttest/story_deploy_undeploy_test.go
> +			It("executes consul CR", func() {
@bisztray not addressed

2022-03-10 08:21 UTC, hochdorf approved these changes

2022-03-10 08:21 UTC, merged