MetricsDomainName deprecated
nokia/industrial-application-framework pull request #38
Opened 2022-03-07 13:05 UTC by helgaber

2022-03-07 13:54 UTC, hochdorf requested changes

2022-03-07 13:54 UTC, hochdorf commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> -                      oneOf:
this was added manually after the auto generation called, so please do not delete it.

2022-03-08 15:19 UTC, hochdorf commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> -
pls add nokia license header

2022-03-09 07:14 UTC, tpaulik approved these changes

2022-03-09 09:04 UTC, hochdorf approved these changes

2022-03-09 09:52 UTC, merged