added application-lib
nokia/industrial-application-framework pull request #44
Opened 2022-03-31 12:46 UTC by bisztray

2022-04-01 15:38 UTC, howardhalili commented on application-lib/pkg/handlers/handlers.go
> +func waitUntilResourcesAreReleased(pna k8sdynamic2.ResourceDescriptor) {
we may need (waiting) timeout in verifying resource deletion.

2022-04-01 15:38 UTC, howardhalili commented on application-lib/pkg/types/common_types.go
> +type PrivateNetworkAccess struct {
is it possible to remove the old(/to be deprecated) fields?

2022-04-05 11:49 UTC, hochdorf requested changes

2022-04-05 11:49 UTC, hochdorf commented on application-lib/pkg/config/config.go
> +const operatorConfigFilename = "operatorconfig.yaml"
why do we need this yaml file here? Shouldn't it be part of the generator?

2022-04-05 11:49 UTC, hochdorf commented on application-lib/pkg/handlers/handlers.go
> +	k8sdynamic2 "github.com/nokia/industrial-application-framework/application-lib/pkg/k8sdynamic"
can you pls rename this import to just k8sdynamic?

2022-04-05 11:49 UTC, hochdorf commented on application-lib/README.md
> +# Kubernetes application library
would be useful to include the relevant parts of the consul-operator readme here

2022-04-05 11:49 UTC, hochdorf commented on application-lib/pkg/monitoring/monitoring.go
> +	kubelib2 "github.com/nokia/industrial-application-framework/application-lib/pkg/kubelib"
pls rename to kubelib

2022-04-05 11:49 UTC, hochdorf commented on application-lib/pkg/types/common_interfaces.go
> +type CommonAppReportedData interface {
do we need this type? as i remember we discussed that it is fully app specific.

2022-04-05 11:49 UTC, hochdorf commented on application-lib/pkg/types/common_types.go
> +	Db string `json:"db"`
this is consul specific, shouldn't be the part of the lib

2022-04-11 09:53 UTC, bisztray commented on application-lib/pkg/config/config.go
> +const operatorConfigFilename = "operatorconfig.yaml"
This yaml contains runtime information on the operator. It is not part of the generation.

2022-04-12 07:33 UTC, bisztray commented on application-lib/pkg/config/config.go
> +	data, err := os.ReadFile(operatorConfigYaml)
fixedf

2022-04-12 07:35 UTC, bisztray commented on application-lib/pkg/monitoring/monitoring.go
> +func (m *Monitor) GetApplicationStatus() common_types.AppStatus {
Fixing this properly is a new feature in itself, updated in an easier manner (not dirty, but not as elaborate as on other examples)

2022-04-12 07:35 UTC, bisztray commented on application-lib/pkg/template/template.go
> +	if strings.Contains(file.Name(), "yaml") {
done

2022-04-12 07:36 UTC, bisztray commented on application-lib/pkg/types/common_types.go
> +type PrivateNetworkAccess struct {
done

2022-04-12 07:36 UTC, bisztray commented on application-lib/pkg/handlers/handlers.go
> +	k8sdynamic2 "github.com/nokia/industrial-application-framework/application-lib/pkg/k8sdynamic"
done

2022-04-12 07:37 UTC, bisztray commented on application-lib/pkg/monitoring/monitoring.go
> +	kubelib2 "github.com/nokia/industrial-application-framework/application-lib/pkg/kubelib"
done

2022-04-12 07:38 UTC, bisztray commented on application-lib/pkg/types/common_interfaces.go
> +type CommonAppReportedData interface {
removed, and moved back to to app-specific types

2022-04-12 11:18 UTC, howardhalili approved these changes

2022-04-12 11:18 UTC, howardhalili commented on application-lib/pkg/monitoring/monitoring.go
> +func (m *Monitor) GetApplicationStatus() common_types.AppStatus {
looks fine given where it is called

2022-04-20 07:55 UTC, howardhalili commented on application-lib/pkg/monitoring/monitoring.go
> +func (m *Monitor) GetApplicationStatus() common_types.AppStatus {
something came out on top of my head, i may not need to rescind my approval but will you open a git issue about this once this is merge?
scenario such as miscalculated resourcerequest/quota (smaller than actually needed) may end up reporting false running status. monitoring is running in this case.

2022-04-20 07:57 UTC, bisztray commented on application-lib/pkg/monitoring/monitoring.go
> +func (m *Monitor) GetApplicationStatus() common_types.AppStatus {
ok

2022-04-20 10:23 UTC, hochdorf commented on application-lib/pkg/monitoring/monitoring.go
> +	kubelib2 "github.com/nokia/industrial-application-framework/application-lib/pkg/kubelib"
it is still kubelib2 not just kubelib

2022-04-20 10:54 UTC, bisztray commented on application-lib/pkg/monitoring/monitoring.go
> +	kubelib2 "github.com/nokia/industrial-application-framework/application-lib/pkg/kubelib"
I hope this is done now

2022-04-20 11:57 UTC, hochdorf approved these changes

2022-04-20 11:57 UTC, merged