Env variable refactor
nokia/industrial-application-framework pull request #45
Opened 2022-04-20 12:24 UTC by bisztray

2022-04-22 12:59 UTC, howardhalili requested changes

2022-04-22 12:59 UTC, howardhalili commented on ndac-operator-sdk/main.go
> +package main
should this be part of this PR? please add readme.

2022-04-25 06:04 UTC, bisztray commented on consul-operator/componenttest/constants.go
> -// Copyright 2022 Nokia
done

2022-04-25 06:04 UTC, bisztray commented on consul-operator/componenttest/constants.go
> +				CustomerNetwork:      "127.0.0.0/28",
done

2022-04-25 06:04 UTC, bisztray commented on consul-operator/componenttest/story_deploy_undeploy_test.go
> +// Copyright 2020 Nokia
done (I'm actually curios how did it end up there)

2022-04-25 06:04 UTC, bisztray commented on consul-operator/config/rbac/role.yaml
> -# Copyright 2021 Nokia
done

2022-04-25 06:04 UTC, bisztray commented on consul-operator/config/rbac/role.yaml
> +  - persistentvolumeclaims
removed

2022-04-25 06:04 UTC, bisztray commented on consul-operator/controllers/operator_controller.go
> +	err := ctrl.NewControllerManagedBy(mgr).
done

2022-04-25 06:04 UTC, bisztray commented on ndac-operator-sdk/main.go
> +package main
removed

2022-04-25 09:19 UTC, howardhalili commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +					[]handlers.DeploymentId{
deployment name is configurable, deployment type is not. not sure how will you handle this in code generation if this code will be included. (maybe not an appropriate topic in this PR).

2022-04-25 09:21 UTC, howardhalili commented on consul-operator/config/operator/operatorconfig.yaml
> +usingPnaLabelKey: ndac.appfw.private-network-access
i think we need to move this value in application-lib, maybe add in handlers const.

also, all fields of operator config seems to be mandatory even for fields that are for optional feature like serviceName. may affect code readability (vs info we are giving) and your code generation.

2022-04-25 09:27 UTC, howardhalili commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +			//consul specific
are you using this comment in code generation? if so, please provide info in readme for future developers of this operator. It may not avoid to accidentally break your code generation/functionality, but at least some guidelines.

2022-04-25 10:06 UTC, bisztray commented on consul-operator/config/operator/operatorconfig.yaml
> +usingPnaLabelKey: ndac.appfw.private-network-access
Here I extracted all consul-specific constants that were embedded in the code mostly as strings.

2022-04-25 10:06 UTC, bisztray commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +			//consul specific
In this PR there is no code generation. This is just a major refactor where everything that is not strictly consul specific were extracted to the application lib.

2022-04-25 10:09 UTC, bisztray commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +					[]handlers.DeploymentId{
we assume that for *basic* cases there is no need to change this code. If need to be changed, it can be done, as this is not in the application-lib.

2022-04-25 11:11 UTC, howardhalili commented on consul-operator/config/operator/operatorconfig.yaml
> +usingPnaLabelKey: ndac.appfw.private-network-access
`ndac.appfw.private-network-access` this label key is not consul specific

2022-04-25 11:28 UTC, howardhalili commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +			//consul specific
i just thought it is used (or will be used) in generator, so guidelines about those kind of things will be helpful for future collaborators.

2022-04-25 11:33 UTC, howardhalili commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +					[]handlers.DeploymentId{
ok, then let's see on generator documentation.

2022-04-25 16:39 UTC, howardhalili requested changes

2022-04-25 16:39 UTC, howardhalili commented on consul-operator/componenttest/suite_initializer_test.go
> +		UsingPnaLabelKey:  "ndac.appfw.private-network-access",
cleanup needed here, update to latest application-lib.

2022-04-26 04:36 UTC, bisztray commented on consul-operator/componenttest/suite_initializer_test.go
> +		UsingPnaLabelKey:  "ndac.appfw.private-network-access",
I need to run test first before changing the operator, and that needed the merge of the application-lib branch.

2022-04-26 06:05 UTC, bisztray commented on consul-operator/config/operator/operatorconfig.yaml
> +usingPnaLabelKey: ndac.appfw.private-network-access
moved to constants, done.

2022-04-26 06:06 UTC, bisztray commented on consul-operator/pkg/monitoring/appstatusmonitor.go
> +			//consul specific
removed comments.

2022-04-26 06:06 UTC, bisztray commented on consul-operator/componenttest/suite_initializer_test.go
> +		UsingPnaLabelKey:  "ndac.appfw.private-network-access",
done

2022-04-26 06:33 UTC, howardhalili approved these changes

2022-04-28 13:00 UTC, closed without merging