Operator sdk refactor
nokia/industrial-application-framework pull request #51
Opened 2022-04-29 12:01 UTC by bisztray

2022-04-29 13:59 UTC, howardhalili requested changes

2022-04-29 13:59 UTC, howardhalili commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> +                    - appNetwork
same as above

2022-04-29 13:59 UTC, howardhalili commented on consul-operator/deployment/resource-reqs/private-network-access.yaml
> +  appNetwork: [[ .PrivateNetworkAccess.AppNetwork ]]
PNA field name should not be changed. PNA CRD owners should do it from the platform if needed/agreed.

2022-05-02 07:21 UTC, bisztray commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> -# Copyright 2021 Nokia
done

2022-05-02 07:21 UTC, bisztray commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> -                oneOf:
done

2022-05-02 07:22 UTC, bisztray commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> +                - appNetwork
yes, it was agreed with @hochdorf

2022-05-02 07:22 UTC, bisztray commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> -                          oneOf:
done

2022-05-02 07:22 UTC, bisztray commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> +                    - appNetwork
done

2022-05-02 07:23 UTC, bisztray commented on consul-operator/deployment/resource-reqs/private-network-access.yaml
> +  appNetwork: [[ .PrivateNetworkAccess.AppNetwork ]]
corrected

2022-05-03 06:26 UTC, hochdorf commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> +                - appNetwork
yes, it will break the compatibility but for the sake of the the new apps that we will create based on consul it's better to rename this param

2022-05-03 06:36 UTC, howardhalili commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> +                - appNetwork
maybe it's also good to delete `PrivateNetworkAccess.ApnUUID` and `PrivateNetworkAccess.AdditionalRoutes` now? (in favor of `PrivateNetworkAccess.Networks[i].ApnUUID` and `PrivateNetworkAccess.Networks[i].AdditionalRoutes`, respectively)

2022-05-03 06:40 UTC, hochdorf approved these changes

2022-05-03 06:42 UTC, hochdorf commented on consul-operator/config/crd/bases/app.dac.nokia.com_consuls.yaml
> +                - appNetwork
yes, agree, if we anyway break the compatibility then this would be the best timing

2022-05-03 08:16 UTC, howardhalili approved these changes

2022-05-03 12:54 UTC, howardhalili requested changes

2022-05-03 12:54 UTC, howardhalili commented on consul-operator/componenttest/crds/app-network-operator-privatenetworkaccesses-crd.yaml
> +                appNetwork:
seems not fixed, we should not change PNA CRD field/paramater names here. it's up to the platform/appfw to do this changes if needed.

2022-05-04 07:16 UTC, howardhalili approved these changes

2022-05-23 14:31 UTC, merged