Upload to bucket
nokia/industrial-application-framework pull request #62
Opened 2022-06-10 12:19 UTC by koltoi

2022-06-15 14:03 UTC, koltoi commented on consul-backup/main.go
> +		time.Sleep(1*time.Hour)
add config map to make the time period configurable

2022-06-23 14:07 UTC, koltoi commented on consul-backup/pkg/s3client/s3client.go
> +	// Backup-operator uses versioning-enabled buckets, that allows to keep multiple variants of an object in the same bucket.
no oversioning

2022-06-23 14:08 UTC, koltoi commented on consul-backup/pkg/s3client/s3client.go
> +/*
remove

2022-06-23 14:17 UTC, koltoi commented on consul-operator/deployment/app-deployment/templates/consul-ss.yaml
> +          image: registry.dac.nokia.com/public/backup:1.0.0
consul-backup

2022-06-27 15:11 UTC, hochdorf commented on consul-backup/main.go
> +	err = serviceconfig.ReadServiceConfig()
is this second readServiceConfig needed?

2022-06-27 15:18 UTC, hochdorf requested changes
pls resolve that last review comment

2022-06-27 15:28 UTC, hochdorf approved these changes

2022-06-28 07:15 UTC, merged