app status monitor change for PNA changed case
nokia/industrial-application-framework pull request #78
Opened 2022-09-22 05:49 UTC by bisztray

2022-09-22 06:00 UTC, bisztray commented
Fixes a problem where upon PNA change the app status update is not called

2022-09-22 11:52 UTC, howardhalili requested changes

2022-09-22 11:52 UTC, howardhalili commented on application-lib/pkg/monitoring/monitoring.go
> +				if m.InstanceAppStatus != status {
i think you also need to update m.InstanceAppStatus after successful update of app specific CR's status.appStatus.

2022-09-22 13:17 UTC, bisztray commented on application-lib/pkg/monitoring/monitoring.go
> +				if m.InstanceAppStatus != status {
Added to line 131 https://github.com/nokia/industrial-application-framework/pull/78/commits/ca6158104ac8c5104fd1107993d8d32d87b319c2

2022-09-22 13:29 UTC, howardhalili commented on application-lib/pkg/monitoring/monitoring.go
> +				if m.InstanceAppStatus != status {
i don't think it's a good place. i recommend to move it in the else clause (to be added) for the if statement in [line 113](https://github.com/bisztray/industrial-application-framework/blob/ca6158104ac8c5104fd1107993d8d32d87b319c2/application-lib/pkg/monitoring/monitoring.go#L113) of current code, that way, we are sure that the app specific CR status update is successful before updating Monitor.InstanceAppStatus.

2022-09-23 07:48 UTC, howardhalili approved these changes

2022-09-23 08:48 UTC, merged